# Site wide configuration

title: Ella's Cookbook
locale: en_US
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! I'm a big fan of cheap, healthy, tasty food, and I'll be posting new recipes each week. 
  
  All prices are in euros, and based on Tescos, although similar prices should be available in most shops.
  Calories are estimates, based on my calculations.
  
logo: logo-black.png
search: true
url: ""
baseurl: "" # the subpath of your site, e.g. /blog

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Ella Cullen
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github:  ellacullen
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
